version: '2.1'

networks:
  default:
    external: true
    name: test_net

services:
  mock:
    container_name: mock
    image: "mock:latest"
    ports:
      - "8081:8081"
    healthcheck:
      test: [ "CMD", "curl", "mock:8081" ]
      timeout: 1s
      retries: 30
    depends_on:
      percona:
        condition: service_healthy

  percona:
    container_name: percona
    image: "percona:5.7"

    environment:
      MYSQL_ROOT_PASSWORD: pass
    ports:
      - "3306:3306"
    volumes:
      - ./sql_config:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "-uroot", "-ppass", "ping", "-h", "percona"]
      timeout: 1s
      retries: 30

  myapp:
    image: "myapp"
    container_name: myapp
    volumes:
      - ./config:/tmp/config
    command: ["/app/myapp", "--config=/tmp/config"]
    ports:
      - "8083:8083"
    healthcheck:
      test: [ "CMD", "curl", "myapp:8083" ]
      timeout: 1s
      retries: 30
    depends_on:
      percona:
        condition: service_healthy
      mock:
        condition: service_healthy

  selenoid:
    image: aerokube/selenoid:latest
    container_name: selenoid
    volumes:
      - ./selenoid_config/config:/etc/selenoid
      - /var/run/docker.sock:/var/run/docker.sock
      - ./selenoid_config/video:/opt/selenoid/video
      - ./selenoid_config/logs:/opt/selenoid/logs
    environment:
      - OVERRIDE_VIDEO_OUTPUT_DIR=./selenoid_config/video
    command: [ "-conf", "/etc/selenoid/browsers.json", "-video-output-dir",
               "/opt/selenoid/video", "-log-output-dir", "/opt/selenoid/logs",
               "-container-network", "test_net" ]
    ports:
      - "4444:4444"

  selenoid-ui:
    container_name: selenoid-ui
    image: "aerokube/selenoid-ui"
    depends_on:
      selenoid:
        condition: service_started
    ports:
      - "8080:8080"
    command: [ "--selenoid-uri", "http://selenoid:4444" ]
